# Site settings
# --------------
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.
baseurl = "/" # The subpath of your site, e.g. / or /blog
languageCode = "fr-fr"
languageLang = "fr"
defaultContentLanguage = "fr"
title = "Pampa Hard Seltzer"
# disable language
disableLanguages = [] # disable language from here
cookieConsent = true

# Build settings
# --------------

# Set the destination the same as the Gulpfile for consistency
destination = "../dist/"

# Categories and tags disabled for an easier start
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]

# Enable this to have links relativized by Hugo
# E.g,  if your /post/first/ page contains a link 
# to /about/, Hugo will rewrite the URL to ../../about/
relativeURLs = false

# Enable to have links open in new tab
hrefTargetBlank = false

# Enable rendering of Emojis in markdown
enableEmoji = true



[params.privacyPolicyUrl]
URL = "privacy-policy"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"
  [[params.plugins.css]]
  URL = "css/cookieconsent.css"
  [[params.plugins.css]]
  URL = "plugins/swiper/swiper-bundle.css"



  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"
  [[params.plugins.js]]
  URL = "plugins/swiper/swiper-bundle.js"
  [[params.plugins.js]]
  URL = "js/age.js"
  [[params.plugins.js]]
  URL = "js/modal.js"



# Site Params
# -------------
[params]
description = '''
Write an awesome description for your new site here. You can edit this
line in config.yml. It will appear in your document head meta (for
Google search results) and in your RSS feed description.
'''
author = "Pampa"

sections = ["hero", "parfums", "pub", "story", "photos", "newsletter"]

googleTagManagerID = "GTM-5XTRRFQ" # Google Analytics works with Google Tag Manager

# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

[params.logo]
    text1 = "Pampa"
    text2 = "Hard Seltzer"

[params.footer]
      copyright = "© Pampa Drinks. Tous droits réservés."
      [params.footer.logo]
        x = "img/general/Pampa-hard_seltzer.png"
        alt = "Pampa Hard Seltzer"
        link = "https://www.pampahardseltzer.com/"



# Preloader
[params.preloader]
enable = true
preloader = "img/general/Pampa-hard_seltzer.png" # use .png , .svg or .gif format

# Site Menus
# See the Hugo docs for usage in layouts
# https://gohugo.io/content-management/menus
 


# Related Content
# ---------------
# Enable the options below to use Hugo's related
# pages feature for related posts, etc.
# https://gohugo.io/content-management/related/
# [related]
#   includeNewer = true
#   threshold = 10
#   toLower = true
#[[related.indices]]
#   name = "Section"
#   weight = 200
#[[related.indices]]
#   name = "keywords"
#   weight = 150
#[[related.indices]]
#   name = "categories"
#   weight = 150
#[[related.indices]]
#   name = "tags"
#   weight = 100
#[[related.indices]]
#   name = "date"
#   pattern = "2006"
#   weight = 10

# English language 
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "© Pampa Drinks. All rights reserved."


# French language 
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "© Pampa Drinks. Tous droits réservés."